# FEATURE EXTRACTION PROJECT

In [27]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv('anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [29]:
def extract_episodes(title):
    check = False
    data = ""
    for i in title:
        if i == ")":
            break
        if check == True:
            data += i
        if i == "(":
            check = True
        
    return data

In [30]:
df['Episodes'] = df['Title'].apply(extract_episodes)
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [31]:
df['Episodes'] = df['Episodes'].str.replace(' eps', '')
print(df['Episodes'].dtype)

str

In [32]:
df['Episodes'] = df['Episodes'].astype(int)
print(df['Episodes'].dtype)

int64

In [33]:
def extract_time(title):
    check = False
    data = ""
    for i in range(len(title)):
        if title[i] == ')':
            for j in range(i+1, i+20):
                data += title[j]

            break
    return data

In [34]:
df['Total_Time'] = df['Title'].apply(extract_time)
df.head()

,Rank,Title,Score,Episodes,Total_Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [35]:
from datetime import datetime

def calculate_months(date_range):
    # split the string into start and end dates
    start_str, end_str = date_range.split(' - ')
    
    # parse the dates
    start = datetime.strptime(start_str.strip(), '%b %Y')
    end = datetime.strptime(end_str.strip(), '%b %Y')
    
    # calculate total months
    months = (end.year - start.year) * 12 + (end.month - start.month)
    
    return months

# apply to the column
df['Months'] = df['Total_Time'].apply(calculate_months)

In [36]:
df.head()

,Rank,Title,Score,Episodes,Total_Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

# Which anime has the highest score?

In [37]:
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,Episodes,Total_Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

# top 5 highest scoring anime

In [38]:
top5 = df.nlargest(5, 'Score')[['Rank', 'Title', 'Score']]
print(top5)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

# Which anime has the highest epoisode count?

In [39]:
df.nlargest(1, 'Episodes')

,Rank,Title,Score,Episodes,Total_Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47

# Animes with top 5 episode count

In [40]:
df.nlargest(5, 'Episodes')

,Rank,Title,Score,Episodes,Total_Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,35
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,17
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,17

# longest running anime

In [41]:
df.nlargest(1, 'Months')

,Rank,Title,Score,Episodes,Total_Time,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110