In [2]:
import numpy as np
import pandas as pd

In [ ]:
# Reading CSV data
df = pd.read_csv("employee_data.csv")
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [6]:
# Reading JSON data
df = pd.read_json('employee_data.json')
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

Data Frame Methods:-

1. df.head() → Returns first 5 rows (or n rows) of the DataFrame

2. df.tail() → Returns last 5 rows (or n rows) of the DataFrame

3. df.sample() → Returns random rows from the DataFrame

4. df.info() → Gives summary of DataFrame (columns, data types, non-null counts)

5. df.shape → Returns tuple of (rows, columns)

6. df.describe() → Generates statistical summary (mean, std, min, max, etc.) for numeric columns

7. df.columns → Returns list of column names

8. df.nunique() → Returns count of unique values in each column

Hello World