In [26]:
import numpy as np
import pandas as pd

In [27]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
column_label = ["Name", "Age", "City", "Salary"] 
list_df = pd.DataFrame(data_list, columns=column_label)
list_df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
# accessing single column from dataframe
list_df["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [30]:
# Accessing multiple column from dataframe
list_df[["Name", "Age","Salary"]]

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

In [31]:
# Adding a new column to the dataframe.
list_df["Designation"] = ["Data Analyst", "Data Scientist", "AI Engineer", "RAG Specialist"]
list_df

    Name  Age      City  Salary     Designation
0   John   28  New York   65000    Data Analyst
1   Anna   34     Paris   70000  Data Scientist
2  Peter   29    Berlin   62000     AI Engineer
3  Linda   42    London   85000  RAG Specialist

In [32]:
# Deleting a column from dataframe
# axis = 0 means column-wise
# axis = 1 means row-wise
list_df.drop('Designation', axis=1,inplace=True)
list_df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

SELECTING ROWS:-

In [33]:
list_df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
list_df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [35]:
list_df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [37]:
list_df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [38]:
list_df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# Selecting part of dataframe
list_df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

CONDITIONAL SELECTION

In [43]:
list_df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
# people above age 30
list_df[list_df['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [46]:
# people above age 30 and city is Paris
list_df[(list_df['Age'] > 30) & (list_df['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000